---
title: "Eksamensspørgsmål 2: Faktor-analyse"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
load("carcass_fa.RData")
library(nFactors)

```

## Opgave 2


```{r, echo=FALSE }
corrplot::corrplot(cor(carcass_fa), order = "hclust", tl.col='black', tl.cex=.75)
```

```{r, include=FALSE}
carcass <- as.data.frame(scale(carcass_fa))

```

```{r, echo=FALSE }
(carcass_eigen <- eigen(cov(carcass))$value)
```


```{r}
FactAnalNoRota <- factanal(carcass, factors = 3, rotation = "none", na.action = na.omit);FactAnalNoRota
```


```{r}
FactAnalNoRota7 <- factanal(carcass, factors = 7, rotation = "none", na.action = na.omit);FactAnalNoRota7
```

```{r, echo=FALSE }
par(mfrow=c(1,1))
plot(FactAnalNoRota$loadings[,1:2], type="n") # set up plot
text(FactAnalNoRota$loadings[,1:2],labels=rownames(FactAnalNoRota$loadings),cex=.7)
```

```{r}
FactAnalVarimaxRota = factanal(carcass, factors = 3, rotation = "varimax",na.action = na.omit, scores = "regression");FactAnalVarimaxRota
```

```{r, echo=FALSE }
pairs(FactAnalNoRota$loadings[,1:3],panel = function(x,y) text(x,y, labels=rownames(FactAnalNoRota$loadings)))
pairs(FactAnalVarimaxRota$loadings[,1:3],panel = function(x,y) text(x,y, labels=rownames(FactAnalVarimaxRota$loadings)))


```